# frozen_string_literal: true

require 'onlyoffice_rake_code_linter'

desc 'Perform check on source files'
task :check_source_files, [:exclude_paths] do |_, args|
  exclude_paths = args.fetch(:exclude_paths, [])
  OnlyofficeRakeCodeLinter::OnlyofficeRakeCodeLinter.file_without_address(exclude_paths: exclude_paths)
  OnlyofficeRakeCodeLinter::OnlyofficeRakeCodeLinter.file_without_lf_ending
  OnlyofficeRakeCodeLinter::OnlyofficeRakeCodeLinter.file_without_address(exclude_paths: exclude_paths)
  OnlyofficeRakeCodeLinter::OnlyofficeRakeCodeLinter.file_without_trailing_newline
end
